/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kmii' at '2/08/16 12:49' with Gradle 2.14
 *
 * @author Kmii, @date 2/08/16 12:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
